version: "3"

services:
  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    depends_on:
      - static-website
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  static-website:
    image: static-website
    container_name: static-website
    build:
      context: ./static-website
    ports:
      - 5001:80
    restart: on-failure
